// Generated by gencpp from file first_pkg/AddTwoIntsRequest.msg
// DO NOT EDIT!


#ifndef FIRST_PKG_MESSAGE_ADDTWOINTSREQUEST_H
#define FIRST_PKG_MESSAGE_ADDTWOINTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace first_pkg
{
template <class ContainerAllocator>
struct AddTwoIntsRequest_
{
  typedef AddTwoIntsRequest_<ContainerAllocator> Type;

  AddTwoIntsRequest_()
    : c(0)
    , d(0)  {
    }
  AddTwoIntsRequest_(const ContainerAllocator& _alloc)
    : c(0)
    , d(0)  {
  (void)_alloc;
    }



   typedef int64_t _c_type;
  _c_type c;

   typedef int64_t _d_type;
  _d_type d;




  typedef boost::shared_ptr< ::first_pkg::AddTwoIntsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::first_pkg::AddTwoIntsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoIntsRequest_

typedef ::first_pkg::AddTwoIntsRequest_<std::allocator<void> > AddTwoIntsRequest;

typedef boost::shared_ptr< ::first_pkg::AddTwoIntsRequest > AddTwoIntsRequestPtr;
typedef boost::shared_ptr< ::first_pkg::AddTwoIntsRequest const> AddTwoIntsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::first_pkg::AddTwoIntsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::first_pkg::AddTwoIntsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace first_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'first_pkg': ['/home/ros/practice/catkin_ws/src/first_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::first_pkg::AddTwoIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first_pkg::AddTwoIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::first_pkg::AddTwoIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::first_pkg::AddTwoIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_pkg::AddTwoIntsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_pkg::AddTwoIntsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::first_pkg::AddTwoIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f169a2f97ba3cbc67f1025198bb39411";
  }

  static const char* value(const ::first_pkg::AddTwoIntsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf169a2f97ba3cbc6ULL;
  static const uint64_t static_value2 = 0x7f1025198bb39411ULL;
};

template<class ContainerAllocator>
struct DataType< ::first_pkg::AddTwoIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "first_pkg/AddTwoIntsRequest";
  }

  static const char* value(const ::first_pkg::AddTwoIntsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::first_pkg::AddTwoIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 c\n\
int64 d\n\
";
  }

  static const char* value(const ::first_pkg::AddTwoIntsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::first_pkg::AddTwoIntsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.c);
      stream.next(m.d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoIntsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::first_pkg::AddTwoIntsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::first_pkg::AddTwoIntsRequest_<ContainerAllocator>& v)
  {
    s << indent << "c: ";
    Printer<int64_t>::stream(s, indent + "  ", v.c);
    s << indent << "d: ";
    Printer<int64_t>::stream(s, indent + "  ", v.d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIRST_PKG_MESSAGE_ADDTWOINTSREQUEST_H
