// Generated by gencpp from file keyboard_control_gpio/keyboard.msg
// DO NOT EDIT!


#ifndef KEYBOARD_CONTROL_GPIO_MESSAGE_KEYBOARD_H
#define KEYBOARD_CONTROL_GPIO_MESSAGE_KEYBOARD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace keyboard_control_gpio
{
template <class ContainerAllocator>
struct keyboard_
{
  typedef keyboard_<ContainerAllocator> Type;

  keyboard_()
    : word()  {
    }
  keyboard_(const ContainerAllocator& _alloc)
    : word(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _word_type;
  _word_type word;





  typedef boost::shared_ptr< ::keyboard_control_gpio::keyboard_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::keyboard_control_gpio::keyboard_<ContainerAllocator> const> ConstPtr;

}; // struct keyboard_

typedef ::keyboard_control_gpio::keyboard_<std::allocator<void> > keyboard;

typedef boost::shared_ptr< ::keyboard_control_gpio::keyboard > keyboardPtr;
typedef boost::shared_ptr< ::keyboard_control_gpio::keyboard const> keyboardConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::keyboard_control_gpio::keyboard_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::keyboard_control_gpio::keyboard_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace keyboard_control_gpio

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'keyboard_control_gpio': ['/home/ros/practice/catkin_ws/src/keyboard_control_gpio/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::keyboard_control_gpio::keyboard_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::keyboard_control_gpio::keyboard_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::keyboard_control_gpio::keyboard_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::keyboard_control_gpio::keyboard_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::keyboard_control_gpio::keyboard_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::keyboard_control_gpio::keyboard_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::keyboard_control_gpio::keyboard_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf5cbdd7f0c6b9eaa898f882ab6eade6";
  }

  static const char* value(const ::keyboard_control_gpio::keyboard_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf5cbdd7f0c6b9eaULL;
  static const uint64_t static_value2 = 0xa898f882ab6eade6ULL;
};

template<class ContainerAllocator>
struct DataType< ::keyboard_control_gpio::keyboard_<ContainerAllocator> >
{
  static const char* value()
  {
    return "keyboard_control_gpio/keyboard";
  }

  static const char* value(const ::keyboard_control_gpio::keyboard_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::keyboard_control_gpio::keyboard_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string word\n\
";
  }

  static const char* value(const ::keyboard_control_gpio::keyboard_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::keyboard_control_gpio::keyboard_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.word);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct keyboard_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::keyboard_control_gpio::keyboard_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::keyboard_control_gpio::keyboard_<ContainerAllocator>& v)
  {
    s << indent << "word: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.word);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KEYBOARD_CONTROL_GPIO_MESSAGE_KEYBOARD_H
